<?php

$cards = fn (string $a, string $b, string $c) => [
    ['icon' => 'fas fa-gauge-high', 'title' => $a, 'text' => 'Une information hiérarchisée pour comprendre vite, décider avec calme et garder une vision nette.', 'items' => ['Interface lisible', 'Données utiles', 'Suivi propre']],
    ['icon' => 'fas fa-shield-halved', 'title' => $b, 'text' => 'Des parcours pensés pour protéger les accès, les opérations sensibles et les documents importants.', 'items' => ['Accès sécurisé', 'Preuves disponibles', 'Contrôles cohérents']],
    ['icon' => 'fas fa-file-lines', 'title' => $c, 'text' => 'Des justificatifs, reçus et informations structurées pour vos besoins comptables et administratifs.', 'items' => ['Reçus PDF', 'Historique clair', 'Archivage simple']],
];
$steps = fn () => [
    ['title' => 'Comprendre le besoin', 'text' => 'La page présente d’abord les informations essentielles pour éviter les zones d’ombre.'],
    ['title' => 'Agir avec méthode', 'text' => 'Chaque parcours met en avant les actions utiles, sans complexité inutile.'],
    ['title' => 'Suivre les preuves', 'text' => 'Les opérations importantes restent associées à des références et documents exploitables.'],
    ['title' => 'Être accompagné', 'text' => 'Le support reste disponible lorsque la situation demande une réponse personnalisée.'],
];
$faq = fn () => [
    ['question' => 'À qui s’adresse cette page ?', 'answer' => 'Aux clients qui veulent comprendre rapidement le service, ses avantages et les étapes à suivre.'],
    ['question' => 'Les informations sont-elles mises à jour ?', 'answer' => 'Oui. Les contenus évoluent avec les services et l’expérience Zuider Bank S.A.'],
    ['question' => 'Puis-je contacter un conseiller ?', 'answer' => 'Oui. Le formulaire de contact permet d’envoyer une demande détaillée au bon interlocuteur.'],
    ['question' => 'Pourquoi cette approche ?', 'answer' => 'Parce qu’une banque moderne doit être claire, sécurisée et utile dès la première lecture.'],
];
$make = fn ($accent, $accentAlt, $image, $eyebrow, $title, $subtitle, $primary, $secondary, $icon, $heroTitle, $heroText, $metrics, $cardsTitle, $stepsTitle, $ctaTitle, $contact = null, $legal = null) => array_filter([
    'accent' => $accent, 'accent_alt' => $accentAlt, 'hero_image' => asset($image), 'eyebrow' => $eyebrow, 'eyebrow_icon' => $icon,
    'title' => $title, 'subtitle' => $subtitle, 'primary_cta' => $primary, 'secondary_cta' => $secondary,
    'hero_icon' => $icon, 'hero_card_title' => $heroTitle, 'hero_card_text' => $heroText, 'metrics' => $metrics,
    'cards_kicker' => 'Bénéfices', 'cards_title' => $cardsTitle, 'cards_intro' => 'Une structure pensée pour rendre chaque information claire, utile et directement exploitable.',
    'cards' => $cards('Clarté immédiate', 'Sécurité visible', 'Preuves exploitables'),
    'steps_kicker' => 'Méthode', 'steps_title' => $stepsTitle, 'steps_intro' => 'Un parcours simple, sérieux et conçu pour réduire les hésitations.', 'steps' => $steps(),
    'faq' => $faq(), 'cta_title' => $ctaTitle, 'cta_text' => 'Passez à une expérience bancaire plus claire, plus moderne et mieux structurée avec Zuider Bank S.A.',
    'contact' => $contact, 'legal_items' => $legal, 'legal_kicker' => 'Cadre officiel', 'legal_title' => 'Informations légales détaillées', 'legal_intro' => 'Les informations importantes sont regroupées pour une lecture simple et transparente.',
]);

return [
    'shared' => [
        'nav_home' => 'Accueil', 'nav_services' => 'Services', 'nav_about' => 'À propos', 'nav_support' => 'Support',
        'client_area' => 'Espace client', 'open_account' => 'Ouvrir un compte', 'first_name' => 'Prénom', 'last_name' => 'Nom',
        'email' => 'Adresse email', 'phone' => 'Téléphone', 'subject' => 'Sujet', 'choose_subject' => 'Choisir un sujet',
        'subject_support' => 'Support client', 'subject_commercial' => 'Ouverture de compte', 'subject_partnership' => 'Partenariat',
        'subject_press' => 'Presse', 'subject_other' => 'Autre demande', 'message' => 'Message',
        'message_placeholder' => 'Expliquez-nous votre besoin. Nous répondrons avec une information claire et exploitable.',
        'privacy_notice' => 'J’accepte que Zuider Bank S.A utilise ces informations pour répondre à ma demande.',
        'send_request' => 'Envoyer ma demande', 'rights' => 'Tous droits réservés.',
    ],
    'pages' => [
        'services_business' => $make('#0b5cff', '#00b8d9', 'images/services.jpg', 'Compte professionnel', 'Un compte professionnel pensé pour décider vite, payer juste et garder le contrôle.', 'Un espace bancaire clair, sécurisé et prêt pour les opérations quotidiennes comme pour les décisions sensibles.', 'Créer mon compte professionnel', 'Parler à un conseiller', 'fas fa-briefcase', 'Une base bancaire solide pour votre activité.', 'Suivi en temps réel, reçus propres, alertes utiles et parcours guidé.', [['value'=>'24/7','label'=>'Accès sécurisé'],['value'=>'PDF','label'=>'Reçus exportables'],['value'=>'Multi','label'=>'Usages professionnels'],['value'=>'Clair','label'=>'Vue des mouvements']], 'Moins de friction bancaire, plus de maîtrise opérationnelle.', 'Un compte ouvert avec méthode.', 'Construisez votre base bancaire professionnelle.'),
        'services_international' => $make('#155eef', '#12b76a', 'images/photo-154.avif', 'Paiements transfrontaliers', 'Des virements internationaux suivis, documentés et compréhensibles.', 'Vos transferts gardent une trace claire avant, pendant et après traitement.', 'Préparer un virement', 'Demander un accompagnement', 'fas fa-earth-europe', 'Chaque transfert garde une trace claire.', 'Montant, bénéficiaire, statut, progression et reçu officiel restent lisibles.', [['value'=>'100%','label'=>'Progression visible'],['value'=>'PDF','label'=>'Preuve officielle'],['value'=>'IBAN','label'=>'Détails contrôlés'],['value'=>'Alerte','label'=>'Action requise']], 'Une expérience internationale plus fiable.', 'Un virement international doit rester traçable.', 'Envoyez vos virements avec plus de visibilité.'),
        'services_treasury' => $make('#167c5b', '#00b8d9', 'images/photo-15.avif', 'Trésorerie pilotée', 'Une trésorerie qui se lit vite et se pilote avec calme.', 'Solde, historique, justificatifs et signaux d’attention deviennent plus faciles à exploiter.', 'Piloter ma trésorerie', 'Voir les services', 'fas fa-chart-line', 'La clarté financière devient un avantage.', 'Comprenez ce qui entre, ce qui sort et ce qui demande attention.', [['value'=>'Vue','label'=>'Solde et mouvements'],['value'=>'Alertes','label'=>'Notifications utiles'],['value'=>'Historique','label'=>'Recherche simple'],['value'=>'Preuves','label'=>'Documents']], 'Une information bien présentée pour mieux piloter.', 'Un rituel simple pour garder le contrôle.', 'Faites de votre compte un outil de pilotage.'),
        'services_cards' => $make('#071a2f', '#d9a441', 'images/zuider-card-3d-hero.png', 'Cartes de paiement', 'Des cartes modernes pour payer, suivre et justifier.', 'Une carte bancaire sérieuse, liée à une expérience claire et sécurisée.', 'Demander ma carte', 'Découvrir le compte', 'fas fa-credit-card', 'Une carte n’est utile que si elle reste contrôlable.', 'Chaque paiement doit pouvoir être compris, retrouvé et justifié.', [['value'=>'3D','label'=>'Carte premium'],['value'=>'Suivi','label'=>'Mouvements visibles'],['value'=>'PDF','label'=>'Preuves'],['value'=>'Sécurité','label'=>'Accès protégé']], 'Une carte belle, mais surtout utile.', 'De la demande au suivi, tout reste lisible.', 'Donnez à vos paiements une carte à la hauteur.'),
        'about_story' => $make('#0b5cff', '#12b76a', 'images/happy-bank-customers.jpg', 'Notre histoire', 'Une banque construite pour remettre de la clarté dans la finance digitale.', 'Zuider Bank S.A avance avec une idée simple : moderniser sans perdre le sérieux bancaire.', 'Ouvrir mon espace', 'Nous contacter', 'fas fa-landmark', 'Confiance, lisibilité, sécurité.', 'Chaque évolution rend les opérations plus compréhensibles et plus faciles à justifier.', [['value'=>'2018','label'=>'Vision initiale'],['value'=>'27','label'=>'Pays desservis'],['value'=>'150+','label'=>'Collaborateurs'],['value'=>'10k+','label'=>'Clients']], 'La modernité bancaire doit inspirer confiance.', 'Une progression pensée pour durer.', 'Découvrez une banque qui avance avec méthode.'),
        'about_careers' => $make('#167c5b', '#0b5cff', 'images/zabra.avif', 'Carrières', 'Construire une banque plus nette, plus sûre et plus humaine.', 'Nous recherchons des profils qui aiment les produits bien faits et les décisions responsables.', 'Envoyer ma candidature', 'Découvrir notre histoire', 'fas fa-people-group', 'Une équipe qui préfère la précision au bruit.', 'Chaque métier contribue à une banque qui inspire confiance.', [['value'=>'Produit','label'=>'Amélioration'],['value'=>'Client','label'=>'Usage réel'],['value'=>'Sécurité','label'=>'Exigence'],['value'=>'Impact','label'=>'Travail visible']], 'Rendre la banque plus simple sans la rendre légère.', 'Un processus clair pour évaluer la contribution.', 'Vous voulez construire une banque plus lisible ?'),
        'about_press' => $make('#7c3aed', '#0b5cff', 'images/photo-154.avif', 'Presse et médias', 'Les ressources presse pour comprendre l’évolution de Zuider Bank S.A.', 'Retrouvez notre positionnement, nos sujets clés et nos informations officielles.', 'Contacter la presse', 'Voir notre histoire', 'fas fa-newspaper', 'Une banque digitale qui assume son sérieux.', 'Innovation, sécurité, traçabilité et expérience client constituent nos angles majeurs.', [['value'=>'Fintech','label'=>'Banque digitale'],['value'=>'Sécurité','label'=>'Confiance'],['value'=>'Europe','label'=>'Multilingue'],['value'=>'B2B','label'=>'Services pro']], 'Des sujets concrets, loin des communiqués creux.', 'Les informations utiles avant publication.', 'Besoin d’informations presse fiables ?'),
        'about_blog' => $make('#f97316', '#0b5cff', 'images/services.jpg', 'Blog bancaire', 'Des articles pour mieux comprendre la banque en ligne.', 'Guides et analyses pour clarifier sécurité, virements, reçus, cartes et trésorerie.', 'Ouvrir mon compte', 'Contacter le support', 'fas fa-pen-nib', 'Une base de lecture utile pour décider.', 'Chaque article aide à comprendre une opération ou éviter une erreur.', [['value'=>'Guides','label'=>'Pratiques'],['value'=>'Sécurité','label'=>'Réflexes'],['value'=>'Finance','label'=>'Gestion'],['value'=>'Preuves','label'=>'Documents']], 'Un blog structuré autour des vrais usages.', 'Nos articles rendent l’action plus facile.', 'Passez de la lecture à l’action.'),
        'support_help' => $make('#0b5cff', '#00b8d9', 'images/zabra.avif', 'Centre d’aide', 'Un centre d’aide conçu pour trouver une réponse, pas pour se perdre.', 'Retrouvez les réponses essentielles sur le compte, la sécurité, les virements et les reçus.', 'Contacter le support', 'Ouvrir un compte', 'fas fa-life-ring', 'Des réponses courtes, utiles et orientées action.', 'Le centre d’aide vous aide à comprendre quoi faire et quel document récupérer.', [['value'=>'Compte','label'=>'Accès'],['value'=>'Sécurité','label'=>'2FA'],['value'=>'Virements','label'=>'Reçus'],['value'=>'Support','label'=>'Assistance']], 'Une aide organisée autour de vos moments bancaires.', 'Une méthode simple pour résoudre plus vite.', 'Besoin d’une réponse personnalisée ?'),
        'support_contact' => $make('#155eef', '#12b76a', 'images/happy-bank-customers.jpg', 'Nous contacter', 'Une question bancaire mérite une réponse claire.', 'Expliquez votre demande : support, compte, partenariat, presse ou question administrative.', 'Écrire au support', 'Consulter l’aide', 'fas fa-headset', 'Un formulaire pensé pour accélérer le traitement.', 'Un bon contexte permet d’éviter les réponses génériques.', [['value'=>'Support','label'=>'Questions client'],['value'=>'Compte','label'=>'Accès'],['value'=>'Presse','label'=>'Média'],['value'=>'Pro','label'=>'Partenariat']], 'Plus votre message est précis, plus la réponse sera utile.', 'Préparez le bon contexte avant d’écrire.', 'Votre demande est prête ?', ['kicker'=>'Formulaire sécurisé','title'=>'Envoyez votre demande à Zuider Bank S.A.','intro'=>'Le formulaire conserve les champs compatibles avec le traitement existant.','cards'=>[['icon'=>'fas fa-envelope','title'=>'Email support','text'=>'support@zuiderbank.com pour les demandes générales.'],['icon'=>'fas fa-building','title'=>'Demandes professionnelles','text'=>'Comptes, cartes, trésorerie ou opérations bancaires.']]]),
        'support_security' => $make('#b42318', '#f97316', 'images/256-bit.webp', 'Sécurité bancaire', 'La sécurité doit se voir dans chaque étape.', 'Zuider Bank S.A protège les accès, structure les opérations sensibles et rend les preuves vérifiables.', 'Ouvrir un compte sécurisé', 'Contacter le support', 'fas fa-shield-halved', 'Une sécurité pensée pour l’usage réel.', 'Authentification, reçus vérifiables et bonnes pratiques rendent la protection concrète.', [['value'=>'2FA','label'=>'Authentification'],['value'=>'QR','label'=>'Vérification'],['value'=>'PDF','label'=>'Preuves'],['value'=>'No','label'=>'Aucun mot de passe par email']], 'La confiance vient de contrôles cohérents.', 'Quatre réflexes pour protéger votre espace.', 'Sécurisez vos opérations avec des preuves visibles.'),
        'support_legal' => $make('#334155', '#0b5cff', 'images/services.jpg', 'Mentions légales', 'Un cadre légal lisible pour utiliser Zuider Bank S.A en confiance.', 'Informations essentielles sur l’éditeur, l’usage du site, les données et les responsabilités.', 'Contacter Zuider Bank S.A', 'Voir la sécurité', 'fas fa-scale-balanced', 'La conformité commence par des informations compréhensibles.', 'Les mentions légales sont regroupées pour une lecture simple et transparente.', [['value'=>'Éditeur','label'=>'Zuider Bank S.A'],['value'=>'Données','label'=>'Gestion encadrée'],['value'=>'Cookies','label'=>'Usage expliqué'],['value'=>'Support','label'=>'Contact']], 'Les points importants avant d’utiliser le site.', 'Un cadre officiel simple et stable.', 'Une question sur le cadre légal ?', null, [['title'=>'Éditeur du site','text'=>'Le site est édité par Zuider Bank S.A.'],['title'=>'Objet du site','text'=>'Le site présente les services bancaires digitaux de Zuider Bank S.A.'],['title'=>'Données personnelles','text'=>'Les données servent à gérer le compte, sécuriser les accès et traiter les demandes.']]),
    ],
];
